### ISSUE TITLE
Question - My phone shows a blank screen and i cannot run in local and web server

### ISSUE THREAD

**Issue by MisteriumEz** [PiotrFLEURY/camcode#10]
My phone doesn't show the reader.
He requests the camera but nothing appears.

Every time I try to run the program on a server localhost, the application shows a screen with no information and gives the following error :

Error: PlatformException(error, TypeError: Cannot read property 'apply' of undefined, null, null)
    at Object.throw_ [as throw] (http://10.0.0.146/dart_sdk.js:5063:11)
    at StandardMethodCodec.decodeEnvelope (http://10.0.0.146/packages/flutter/src/services/system_channels.dart.lib.js:1351:19)
    at platform_channel.MethodChannel.new._invokeMethod (http://10.0.0.146/packages/flutter/src/services/system_channels.dart.lib.js:1500:47)
    at _invokeMethod.next (<anonymous>)
    at http://10.0.0.146/dart_sdk.js:37788:33
    at _RootZone.runUnary (http://10.0.0.146/dart_sdk.js:37659:59)
    at _FutureListener.thenAwait.handleValue (http://10.0.0.146/dart_sdk.js:32861:29)
    at handleValueCallback (http://10.0.0.146/dart_sdk.js:33413:49)
    at Function._propagateToListeners (http://10.0.0.146/dart_sdk.js:33451:17)
    at _Future.new.[_completeWithValue] (http://10.0.0.146/dart_sdk.js:33299:23)
    at async._AsyncCallbackEntry.new.callback (http://10.0.0.146/dart_sdk.js:33320:35)
    at Object._microtaskLoop (http://10.0.0.146/dart_sdk.js:37926:13)
    at _startMicrotaskLoop (http://10.0.0.146/dart_sdk.js:37932:13)
    at http://10.0.0.146/dart_sdk.js:33667:9

I'm new on flutter and I'm testing your package, would appreciate your answer c:

And sorry for my bad english, i'm a brazillian guy.

**Comment by PiotrFLEURY** [comment]
Hi @MisteriumEz 

Don't worry for your english. I'm French so my english will be perfect also^^

Can provide me more informations about your use case ?

What is your phone ? (iphone, Android)

Which Javascript library did you provided to Camcode in order to decode barcodes ?

I see that you are running the app in HTTP. Some web browser and some phones (iPhone especially) does not allow to use the camera in HTTP.

You can try to run your app in HTTPS with `live-server` from npmjs [https://www.npmjs.com/package/live-server-https](https://www.npmjs.com/package/live-server-https)
Run it with `buid/web` argument.

If nothing works, can you share me your code or a usage example on a Github repository ? I would be pleased to try to help.

**Comment by MisteriumEz** [comment]
Thanks for listening.

Since I'm really new to the language, I just copied the code from your example to test it.

Starting the test with flutter's default run, it works fine.

I'll send it along with an https build that's hosted on surge.sh.

In any case I'll leave the repository down here.

On the login screen the user is "teste@gmail.com" and the password is "123"

Follow with the link to surge.sh
Please unveil my test screen hahaha


https://github.com/MisteriumEz/projetinho_show
https://royal-discussion.surge.sh/#/

**Comment by PiotrFLEURY** [comment]
Hi @MisteriumEz 

Sorry for the response time. I'm in holidays.

I've tested your app on iPhone and all works fine for me. 
Do you still get some issue ?
