### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by HKTareen** [PiotrFLEURY/camcode#21]
MissingPluginException(No implementation found for method initialize on channel camcode)
 #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (15395): <asynchronous suspension>
E/flutter (15395): #1      _CamCodeScannerState.initialize (package:camcode/cam_code_scanner.dart:82:18)
E/flutter (15395): <asynchronous suspension>

**Comment by PiotrFLEURY** [comment]
Hi @HKTareen 

Thank you for your feedback. Which platform are you targeting ? camcode works only for the Web.

**Comment by HKTareen** [comment]
i am targetting Android Platform  but you have mentioned that it works for Android, IOS and web as mentioned in https://pub.dev/packages/camcode

**Comment by PiotrFLEURY** [comment]
Unfortunately pub.dev just scanned my repository. As it contains android directory it is marked as supporting android. I don't really know if I can juste delete the android directory. Never saw that before.
